[package]
name = "ledger-parser-combinators"
version = "0.1.0"
authors = ["Jonathan D.K. Gibbons <jonored@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

arrayvec = "0.7.1"
generic-array = "0.14.4"
generic-arrayvec = "0.3.0"
log = "0.4.14"
