[package]
name = "ledger-parser-combinators"
version = "0.1.0"
authors = ["Jonathan D.K. Gibbons <jonored@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
